apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/maguilar-redhat/maguilar-hello-world?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: hello-world
    appstudio.openshift.io/component: hello-world
    pipelines.appstudio.openshift.io/type: build
  name: hello-world-on-pull-request
  namespace: oeo-cicada-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads/oeo-cicada-tenant/hello-world:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: docker-build-oci-ta
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:devel@sha256:6ccd7b4807fd48a7be18b6ca13fc6f6eb8c94ffc3dd48ba1f2d6bd3cdb9412e6
    - name: kind
      value: pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'